apiVersion: apps/v1
kind: Deployment
metadata:
  name: driverMgr
  labels:
    app: driverMgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driverMgr
  template:
    metadata:
      labels:
        app: driverMgr
    spec:
      containers:
        - name: driverMgr
          image: username/driverMgr:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5